name: jokes_repository
description: Repository to manage the jokes in Jokes App.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  jokes_api:
    path: ../jokes_api
  jokes_storage:
    path: ../jokes_storage

dev_dependencies:
  coverage: ^1.1.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  mocktail: ^0.2.0
  test: ^1.16.4