name: jokes_api
description: A library to fetch jokes from API.
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.4.0

dev_dependencies:
  coverage: ^1.1.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  mocktail: ^0.2.0
  test: ^1.20.1

